[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
favorites = "CyimdyD5RbGjdZhtTT8n6ZDxjU5er2SGV87fwGQ86U33"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 20000
